In [1]:
import numpy as np

In [2]:
# массив-скаляр
s = np.array(5)
print("Скаляр S:", s)

Скаляр S: 5


In [4]:
print("shape:", s.shape, "| ndim:", s.ndim, "|dtype:", s.dtype, "nbytes:", s.nbytes)

shape: () | ndim: 0 |dtype: int64 nbytes: 8


In [6]:
a = np.zeros(10)
print("Вектор а = ", a)

Вектор а =  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
print("shape:", a.shape, "| ndim:", a.ndim, "|dtype:", a.dtype, "nbytes:", a.nbytes)

shape: (10,) | ndim: 1 |dtype: float64 nbytes: 80


In [8]:
a = np.arange(10, 50) # вектор со значениями от 10 до 49
print("Вектор а=", a)

Вектор а= [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
print("shape:", a.shape, "| ndim:", a.ndim, "|dtype:", a.dtype, "nbytes:", a.nbytes, "| size:", a.size)

shape: (40,) | ndim: 1 |dtype: int64 nbytes: 320 | size: 40


In [13]:
a = np.arange(9).reshape(3, 3)
print("Matrix (3x3) a:", a)

Matrix (3x3) a: [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [14]:
print("shape:", a.shape, "| ndim:", a.ndim, "|dtype:", a.dtype, "nbytes:", a.nbytes, "| size:", a.size)

shape: (3, 3) | ndim: 2 |dtype: int64 nbytes: 72 | size: 9


In [15]:
a = np.array([1, 2, 0, 0, 4, 0])

idx = np.nonzero(a)
print("Индексы ненулевых элементов:", idx)

Индексы ненулевых элементов: (array([0, 1, 4]),)


In [16]:
a = np.random.rand(3, 3, 3)

print("массив а:", a)

массив а: [[[0.35749842 0.11471458 0.86865795]
  [0.38904542 0.23255762 0.89916018]
  [0.99490094 0.2939919  0.99834877]]

 [[0.70066648 0.65679104 0.39709933]
  [0.42161791 0.42879296 0.65135776]
  [0.52896433 0.52595775 0.01941636]]

 [[0.16828655 0.34359156 0.67370938]
  [0.64739561 0.34299791 0.11501529]
  [0.1663025  0.3118758  0.79736726]]]


In [17]:
print("shape:", a.shape, "| ndim:", a.ndim, "|dtype:", a.dtype, "nbytes:", a.nbytes, "| size:", a.size)

shape: (3, 3, 3) | ndim: 3 |dtype: float64 nbytes: 216 | size: 27


In [19]:
a = np.random.rand(10, 10)
print("Matrix a (10x10)", a)
print("shape:", a.shape, "| ndim:", a.ndim)

Matrix a (10x10) [[5.88664142e-01 9.88024218e-01 9.98296738e-01 8.36159366e-01
  8.64479901e-01 2.07278783e-01 2.56084132e-01 6.25970622e-01
  9.08218059e-01 6.00438564e-01]
 [5.82346151e-01 4.58890138e-01 7.83301145e-01 2.98625877e-01
  1.05453165e-01 8.35744323e-01 3.29813707e-01 2.76989968e-01
  2.44825092e-01 7.48148730e-01]
 [9.51020760e-01 4.17757718e-01 8.99679483e-01 8.96761485e-01
  8.59539043e-01 2.53793477e-01 2.55339729e-01 1.19849655e-01
  6.92778846e-01 9.22165196e-03]
 [9.52811591e-02 2.01620093e-01 3.23926795e-01 4.52381319e-01
  3.53775126e-01 4.78589768e-01 3.51424821e-02 5.45534970e-01
  3.52330506e-02 4.80458788e-01]
 [5.24381094e-02 7.08809223e-01 8.09319414e-01 9.33981132e-01
  1.01372181e-01 9.23194781e-01 1.17156951e-01 7.30229341e-02
  3.64882245e-01 7.62189559e-01]
 [9.41672031e-01 8.99539663e-01 3.87124185e-01 6.32119489e-01
  2.06408217e-01 3.10233174e-01 3.53236770e-01 5.23811060e-01
  4.05074065e-01 5.72142723e-01]
 [9.36997948e-01 7.05809181e-01 9.3149505

In [20]:
print("Минимальное значение:", np.min(a))

Минимальное значение: 0.00035743151424394437


In [21]:
print("Максимальное значение:", np.max(a))

Максимальное значение: 0.9982967383434249


In [22]:
max = np.max(a)
print("Max val:", max)

Max val: 0.9982967383434249


In [23]:
a = np.random.rand(30)
print("Вектор а:", a)

Вектор а: [0.56642512 0.20450933 0.08704827 0.93610981 0.82124412 0.96599013
 0.94476206 0.21273188 0.80546982 0.0813641  0.66580152 0.94865479
 0.70195794 0.66021788 0.20770159 0.57371248 0.72335971 0.25850424
 0.35594257 0.53384616 0.52008407 0.64251369 0.97751665 0.55073306
 0.97160306 0.92080459 0.18926344 0.91134538 0.49523896 0.053068  ]


In [24]:
mean = np.mean(a)
print("Среднее значение:", mean)

Среднее значение: 0.582917480377042


In [25]:
a = np.ones((3, 3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [26]:
a[1:-1, 1:-1] = 0
print("Массив 3х3 с единицами по границе и нулями внутри:", a)

Массив 3х3 с единицами по границе и нулями внутри: [[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [27]:
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [28]:
idx = np.unravel_index(99, (6, 7, 8))
print("Индекс 100-го элемента:", idx)

Индекс 100-го элемента: (1, 5, 3)


In [30]:
a = np.ones((6, 7, 8))
print(a)

[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1

In [32]:
# Матрица А размером 5х3
A = np.random.rand(5, 3)

# Матрица B размером 3x2
B = np.random.rand(3, 2)

In [33]:
print(A)

[[0.97281639 0.40427197 0.66513731]
 [0.69107373 0.86297863 0.38690652]
 [0.5385481  0.70881363 0.46745997]
 [0.01220584 0.34651802 0.09313017]
 [0.1589258  0.22988898 0.8430689 ]]


In [34]:
print(B)

[[0.27663797 0.88545174]
 [0.19942781 0.87672842]
 [0.09969468 0.93922741]]


In [35]:
C = np.dot(A, B)
print(C)

[[0.41605168 1.84053389]
 [0.4018517  1.73190354]
 [0.33694328 1.53734663]
 [0.08176651 0.40208029]
 [0.17386065 1.13410474]]


In [36]:
print("Матрица A shape:", A.shape)
print("Матрица B shape:", B.shape)
print("Результат C shape:", C.shape)
print("Матрица C:\n", C)

Матрица A shape: (5, 3)
Матрица B shape: (3, 2)
Результат C shape: (5, 2)
Матрица C:
 [[0.41605168 1.84053389]
 [0.4018517  1.73190354]
 [0.33694328 1.53734663]
 [0.08176651 0.40208029]
 [0.17386065 1.13410474]]
