In [38]:
import numpy as np

In [3]:
# умножение матриц . согласование форм (2Х3) * (3Х2)
A = np.array([[1, 2, 3],
             [4, 5, 6]])
B = np.array([[10, 20],
             [30, 40],
             [50, 60]])

print("A:\n", A)
print("B:\n", B)
print("\n\nA.shape:", A.shape, "|   B.shape:", B.shape)

A:
 [[1 2 3]
 [4 5 6]]
B:
 [[10 20]
 [30 40]
 [50 60]]


A.shape: (2, 3) |   B.shape: (3, 2)


In [6]:
# матричное произведение
# dot , @
C = np.dot(A, B)
print("C =", C)
# (2, 2)
print("Shape C:", C.shape)

C = [[220 280]
 [490 640]]
Shape C: (2, 2)


In [9]:
# поэлементное умножение массивов ОДИНАКОВОЙ формы
A = np.array([[1, 2, 3],
              [4, 5, 6]])
B = np.array([[10, 20, 30],
             [40, 50, 60]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A.Shape", A.shape, "B.Shape", B.shape)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[10 20 30]
 [40 50 60]]
A.Shape (2, 3) B.Shape (2, 3)


In [11]:
# Поэлементное умножение
C = A * B
print("Matrix C:\n", C)
print("C.shape:", C.shape)

Matrix C:
 [[ 10  40  90]
 [160 250 360]]
C.shape: (2, 3)


In [12]:
# транспонирование матрицы (поворот осей)
M = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Matrix M:\n", M)
print("M.Shape", M.shape)

Matrix M:
 [[1 2 3]
 [4 5 6]]
M.Shape (2, 3)


In [14]:
# Транспонирование (строки становятся столбцами)
T = M.T
print("T Matrix\n", T)

T Matrix
 [[1 4]
 [2 5]
 [3 6]]


In [15]:
print("T.shape:", T.shape)

T.shape: (3, 2)


In [17]:
# Выборка элементов по условию. Булева Маска.
x = np.array([-3, -1, 0, 1, 2 , 3])
print("x:", x)

x: [-3 -1  0  1  2  3]


In [18]:
print("x.shape:", x.shape)

x.shape: (6,)


In [19]:
mask = x > 0 # маска - только положительные элементы
print("mask:", mask, " | dtype:", mask.dtype)

mask: [False False False  True  True  True]  | dtype: bool


In [20]:
# отбор по маске
pos = x[mask]
print("Положительные элементы:", pos, "| Shape:", pos.shape)

Положительные элементы: [1 2 3] | Shape: (3,)


In [21]:
print("x:", x)

x: [-3 -1  0  1  2  3]


In [22]:
print("x.shape:", x.shape)

x.shape: (6,)


In [33]:
# комбинированные условия
x = np.arange(-5, 6)
print("x:", x)

x: [-5 -4 -3 -2 -1  0  1  2  3  4  5]


In [34]:
# выберем только положительнввые четные числа
mask = (x > 0) & (x % 2 == 0)
print("mask:", mask)

mask: [False False False False False False False  True False  True False]


In [35]:
res = x[mask]
print("Положительные четные:", res, "| shape:", res.shape)

Положительные четные: [2 4] | shape: (2,)


In [36]:
import numpy as np

# Булева индексация: изменение массива по месту
M = np.arange(-6, 6).reshape(3, 4)   # матрица 3×4 от -6 до 5
print("M (до):\n", M)

# Условие: элементы меньше 0
mask = M < 0
print("\nmask:\n", mask)

# Замена отрицательных значений на 0
M[mask] = 0
print("\nM (после, отрицательные заменены на 0):\n", M)


M (до):
 [[-6 -5 -4 -3]
 [-2 -1  0  1]
 [ 2  3  4  5]]

mask:
 [[ True  True  True  True]
 [ True  True False False]
 [False False False False]]

M (после, отрицательные заменены на 0):
 [[0 0 0 0]
 [0 0 0 1]
 [2 3 4 5]]


In [41]:
# gпрямое изменение массива
M = np.arange(-6, 6).reshape(3, 4)
print("Исходная матрица M:\n", M)

Исходная матрица M:
 [[-6 -5 -4 -3]
 [-2 -1  0  1]
 [ 2  3  4  5]]


In [42]:
# элементы меньше 0
mask = M < 0
print("Mask:\n", mask)

Mask:
 [[ True  True  True  True]
 [ True  True False False]
 [False False False False]]


In [43]:
# Меняем отрицательные значения на 0 (по маске)
M[mask] = 0
print("Матрица M после валидационного условия (маски):\n", M)

Матрица M после валидационного условия (маски):
 [[0 0 0 0]
 [0 0 0 1]
 [2 3 4 5]]


In [44]:
# условное преобразование с where
x = np.array([-3, -1, 0, 1 , 2 , 3])
print("x:", x, "|  shape:", x.shape)

x: [-3 -1  0  1  2  3] |  shape: (6,)


In [45]:
y = np.where(x >= 0, x**2, -1)
print("y:", y, "| shape:", y.shape)

y: [-1 -1  0  1  4  9] | shape: (6,)


In [48]:
# Сумма по осям в матрице
M = np.arange(1,13).reshape(3, 4)
print("M:", M)
print("M.shape:", M.shape)

M: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
M.shape: (3, 4)


In [49]:
# Сумма всех элементов
total = M.sum()
print(total)

78


In [50]:
# сумма по строкам
row_sum = M.sum(axis=1) # вдоль строк
print("сумма по строкам:", row_sum, "shape:", row_sum.shape)

сумма по строкам: [10 26 42] shape: (3,)


In [51]:
# сумма по столбцам
col_sum = M.sum(axis=0) # вдоль столбцов
print("суммы по столбцам:", col_sum, "Shape:", col_sum.shape)

суммы по столбцам: [15 18 21 24] Shape: (4,)


In [55]:
M = np.arange(1,13).reshape(3, 4)
print("M:", M)
print("M.shape:", M.shape)

# среднее всех элементов
mean_total = M.mean()
print("Среднее значение всех элементов:", mean_total)

M: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
M.shape: (3, 4)
Среднее значение всех элементов: 6.5


In [56]:
mean_rows = M.mean(axis=1)
print("Среднее по строкам:", mean_rows, "Shape:", mean_rows.shape)

mean_cols = M.mean(axis=0)

print("Среднее по столбцам:", mean_cols, "Shape:", mean_cols.shape)

Среднее по строкам: [ 2.5  6.5 10.5] Shape: (3,)
Среднее по столбцам: [5. 6. 7. 8.] Shape: (4,)
